[package]
name = "NoiseG8"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "TODO"

[workspace.package]
homepage = "zmann.org"
version = "0.0.0"
edition = "2021"
authors = ["ZMANN <info@zmann.org>"]
license = "GPL-3.0-or-later"

[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { workspace = true }
nih_plug_egui = { path = "crates/nih_plug_egui" }
atomic_float = "0.1"

[workspace.dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git" }
egui = { version = "0.24", default-features = false }
egui_glow = { version = "0.24", optional = false }
baseview = { git = "https://github.com/RustAudio/baseview.git", rev = "1d9806d5bd92275d0d8142d9c9c90198757b9b25" }
raw-window-handle = "0.4"

[workspace]
members = [
    "crates/nih_plug_egui",
    "crates/egui_baseview",
    "xtask"
]

[profile.release]
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
